name: session-11
channels:
  - bioconda
  - eaton-lab
dependencies:
  - numpy
  - pandas
  - toyplot
  - jellyfish
  - spades
  - cutadapt
  - samtools
  - sra-tools
  - minimap2
  - miniasm
  - racon
  - bandage

  #- canu
  #- pilon
  #- blast
